//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductDashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User_Product()
        {
            this.User_Prod_Qty = new List<User_Prod_Qty>();
        }
    
        public int user_prod_id { get; set; }
        public int user_id { get; set; }
        public int product_id { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Prod_Qty> User_Prod_Qty { get; set; }
    }
}
